### ISSUE TITLE
Wrong Junction/Short in Schematic

### ISSUE THREAD

**Issue by BluPhoenix** [tamanishi/Pinky4#4]
There is a Junction at the J1 connector shorting the A (Data) and D (VCC) inputs. 
![image](https://user-images.githubusercontent.com/5477574/175052266-6c0d8790-6a18-4724-9557-583a9521dc42.png)

**Comment by tamanishi** [comment]
Thanks for your comment.

I checked with Kicad 5 on my mac and it was not short-circuited. It wasn't connected in PCB Editor either. 
(Check the images below).

And when I checked it in Kicad 6, it was shorted in Schematic Editor as you said but not connected in PCB Editor.

I guess the problem is caused by Kicad 6 or something.

<img width="1419" alt="Screenshot 2022-06-25 at 12 21 13" src="https://user-images.githubusercontent.com/1237835/175756889-8b08dfa1-7e77-4f91-a386-e340878d6235.png">
<img width="1602" alt="Screenshot 2022-06-25 at 12 24 42" src="https://user-images.githubusercontent.com/1237835/175756892-f381db51-4903-49ca-8026-7a2857f9d258.png">
<img width="1591" alt="Screenshot 2022-06-25 at 12 25 03" src="https://user-images.githubusercontent.com/1237835/175756895-9cf41a2a-a096-4275-a954-ef2afac4dcde.png">

**Comment by tamanishi** [comment]
The Kicad developer says that in Kicad 6, this is "as-designed" behavior. Sorry for the inconvenience, please use Kicad 5 for a while.
https://gitlab.com/kicad/code/kicad/-/issues/10235
https://gitlab.com/kicad/code/kicad/-/issues/11760
https://gitlab.com/kicad/code/kicad/-/issues/11831

**Comment by BluPhoenix** [comment]
Hi thanks for the quick replies. Kind of weird of KiCAD to introduce an update that potentially changes connectivity.
For myself I'd simply move the VCC symbol a bit and remove the junction and then use KiCAD 6.

Just wanted to inform people of this issue before someone unknowingly updates the PCB Components and nets from schematic and doesn't notice this.
